version: "3.9"

services:

  master_node:
    build:
      context: .
      dockerfile: docker_build/master.Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - worker_node_1
      - worker_node_2
      - worker_node_3
    environment:
      WORKERS: "http://worker_node_1:8000/process,http://worker_node_2:8000/process,http://worker_node_3:8000/process"

  worker_node_1:
    build:
      context: .
      dockerfile: docker_build/worker.Dockerfile
    environment:
      - WORKER_ID=1

  worker_node_2:
    build:
      context: .
      dockerfile: docker_build/worker.Dockerfile
    environment:
      - WORKER_ID=2

  worker_node_3:
    build:
      context: .
      dockerfile: docker_build/worker.Dockerfile
    environment:
      - WORKER_ID=3
